[package]
name = "updns"
version = "0.1.7"
edition = "2021"

authors = ["wyhaya <wyhaya@gmail.com>"]
description = "DNS proxy tool"
homepage = "https://github.com/wyhaya/updns"
repository = "https://github.com/wyhaya/updns.git"
license = "MIT"
readme = "README.md"

keywords = [
    "dns",
    "dns-server",
    "dns-proxy",
    "udp"
]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
clap = { version = "3.2.22", features = ["cargo"] }
dirs = "4.0.0"
futures-util = "0.3.21"
lazy_static = "1.4.0"
logs = "0.7.1"
regex = "1.5.5"
tokio = { version = "1.18.5", features = ["rt-multi-thread", "macros", "fs", "io-util", "net", "time", "sync"] }
env_logger = "0.9.0"
log = "0.4.17"
chrono = "0.4.31"
