[package]
name = "updns"
version = "0.1.0"
edition = "2018"

authors = ["wyhaya <wyhaya@gmail.com>"]
description = "DNS proxy tool"
homepage = "https://github.com/wyhaya/updns"
repository = "https://github.com/wyhaya/updns.git"
license = "MIT"
readme = "README.md"

keywords = [
    "dns",
    "dns-server",
    "dns-proxy",
    "udp"
]

[dependencies]
ace = "0.0.2"
dirs = "2.0.2"
futures = "0.3.1"
lazy_static = "1.4.0"
regex = "1.3.1"
time = "0.1.42"
tokio = "0.2.0-alpha.6"